name: Increment Visit Counter

on:
  workflow_dispatch:  # Allows manual triggering via the GitHub Actions tab

jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Ensure this is your default branch

      - name: Ensure counter.json exists
        run: |
          if [ ! -f counter.json ]; then
            echo '{"visits": 0}' > counter.json  # If the file doesn't exist, create it with an initial visit count of 0
          fi

      - name: Fetch current visit count
        id: fetch_counter
        run: |
          echo "Fetching current visit count from counter.json..."
          COUNTER_CONTENT=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/contents/counter.json)

          echo "$COUNTER_CONTENT" > response.json

          # Extract content and decode from base64
          echo "$COUNTER_CONTENT" | jq -r '.content' | base64 --decode > counter.json
          
          # Extract visit count from the decoded file
          VISITS=$(jq -r '.visits' counter.json)
          echo "VISITS=$VISITS" >> $GITHUB_ENV  # Set the visit count as an environment variable

      - name: Increment visit count
        run: |
          NEW_VISITS=$((VISITS + 1))  # Increment the visit count by 1
          echo "Incrementing visit count to: $NEW_VISITS"
          jq --argjson count "$NEW_VISITS" '.visits = $count' counter.json > tmp.json && mv tmp.json counter.json  # Update the counter.json file

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'  # Set the Git username for commits
          git config --global user.email 'github-actions@github.com'  # Set the Git user email for commits
          git add counter.json  # Stage the updated counter.json file
          if git diff --cached --quiet; then
            echo "No changes to commit."  # If there are no changes, do nothing
          else
            git commit -m "Increment visit counter"  # Commit the change
            git push https://x-access-token:${{ GH_TOKEN }}@github.com/ALessCoolApple1/GYATGAMES.ia.git  # Push the change to your repository
          fi
