name: Increment Visit Counter

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch current visit count
        id: fetch_counter
        run: |
          echo "Fetching current visit count from counter.json..."
          COUNTER_CONTENT=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/contents/counter.json)
          VISITS=$(echo $COUNTER_CONTENT | jq -r '.content' | base64 --decode | jq .visits)
          echo "Current visit count: $VISITS"
          echo "VISITS=$VISITS" >> $GITHUB_ENV

      - name: Increment visit count
        run: |
          NEW_VISITS=$((VISITS + 1))
          echo "Incremented visit count: $NEW_VISITS"
          NEW_CONTENT=$(jq --arg new_visits "$NEW_VISITS" '.visits = ($new_visits | tonumber)' counter.json)
          echo "$NEW_CONTENT" > counter.json

      - name: Commit updated visit count
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add counter.json
          git commit -m "Increment visit counter"
          git push
