name: Increment Visit Counter

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes

permissions:
  contents: write  # Explicitly allow write access to the repository

jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Ensure counter.json exists
        run: |
          if [ ! -f counter.json ]; then
            echo '{"visits": 0}' > counter.json
          fi

      - name: Fetch current visit count
        id: fetch_counter
        run: |
          echo "Fetching current visit count from counter.json..."
          COUNTER_CONTENT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/contents/counter.json)
          echo "$COUNTER_CONTENT" > response.json
          echo "$COUNTER_CONTENT" | jq -r '.content' | base64 --decode > counter.json
          VISITS=$(jq -r '.visits' counter.json)
          echo "VISITS=$VISITS" >> $GITHUB_ENV

      - name: Increment visit count
        run: |
          NEW_VISITS=$((VISITS + 1))
          echo "Incrementing visit count to: $NEW_VISITS"
          jq --argjson count "$NEW_VISITS" '.visits = $count' counter.json > tmp.json && mv tmp.json counter.json

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add counter.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Increment visit counter"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
